schema_version = "1.1"
artifacts = []

[task]
name = "terminal-bench/filter-js-from-html"
description = "Evaluates the agent's ability to create a robust XSS filter that removes JavaScript from HTML files while preserving legitimate HTML structure and content."
keywords = ["security"]

[[task.authors]]
name = "Nicholas Carlini"
email = "nicholas@carlini.com"

[metadata]
author_name = "Nicholas Carlini"
author_email = "nicholas@carlini.com"
difficulty = "medium"
category = "security"
tags = ["security"]
expert_time_estimate_min = 45.0
junior_time_estimate_min = 480.0

[verifier]
timeout_sec = 1800.0
network_mode = "no-network"

[verifier.env]


[agent]
timeout_sec = 1800.0
network_mode = "no-network"

[environment]
docker_image = "prime/primeintellect/pitb21-filter-js-from-html:683af1708"
build_timeout_sec = 600.0
cpus = 1
memory_mb = 8192
storage_mb = 10240
gpus = 0
mcp_servers = []
network_mode = "no-network"

[environment.env]


[solution]

[solution.env]

